trigger:
- main  

pool:
  name: MySelfHostedPool 
  demands:
  - agent.name -equals YourAgentName  

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.0.x'  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'webapp'
